import type { NextPage } from 'next'
import Head from 'next/head'

import NavBar from '../components/NavBar'
import Disconnected from '../components/Disconnected'
import Connected from '../components/Connected'
import styles from '../styles/Home.module.css'
import {
  Box,
  Center,
  Spacer,
  Stack
} from '@chakra-ui/react'
import { useWallet } from '@solana/wallet-adapter-react';

const Home: NextPage = () => {
  const {connected } = useWallet();

  return (
    <div className={styles.container}>
      <Head>
        <title>Ikon Buildoors</title>
        <meta name="The NFT collection for IKON Buildoors" content="Generated by Turtles" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box 
        w='full' 
        h='calc(100vh)' 
        bgImage={"url(/home-background.svg)"}
        backgroundPosition='center'

      >
        <Stack
          w='full'
          h='calc(100vh)'
          justify='center'
        >
          <NavBar />
          <Spacer />
          {/* if connected, then this otherwise then that */}
          <Center>
            {connected ? <Connected /> : <Disconnected />}
          </Center>
          <Spacer />
          <Center>
            <Box color='white'>
              <a href='https://twitter.com/_buildspace' target='_blank' rel='noopener noreferrer'>
                Built with Buildspace 
              </a>
            </Box>
          </Center>
        </Stack>

      </Box>

    </div>
  )
}

export default Home
